public class TableCodeGen
{
	private const string codeTemplate = "// This code automatically generated by TableCodeGen\nusing UnityEngine;\nusing System.Collections;\nusing System.Collections.Generic;\n\npublic class $CLASS\n{\n\tpublic class Row\n\t{\n$ROW_MEMBER_CODE\n\t}\n\n\tList<Row> rowList = new List<Row>();\n\tbool isLoaded = false;\n\n\tpublic bool IsLoaded()\n\t{\n\t\treturn isLoaded;\n\t}\n\n\tpublic List<Row> GetRowList()\n\t{\n\t\treturn rowList;\n\t}\n\n\tpublic void Load(TextAsset csv)\n\t{\n\t\trowList.Clear();\n\t\tstring[][] grid = CsvParser2.Parse(csv.text);\n\t\tfor(int i = 1 ; i < grid.Length ; i++)\n\t\t{\n\t\t\tRow row = new Row();\n$ROW_READ_CODE\n\t\t\trowList.Add(row);\n\t\t}\n\t\tisLoaded = true;\n\t}\n\n\tpublic int NumRows()\n\t{\n\t\treturn rowList.Count;\n\t}\n\n\tpublic Row GetAt(int i)\n\t{\n\t\tif(rowList.Count <= i)\n\t\t\treturn null;\n\t\treturn rowList[i];\n\t}\n\n$FIND_CODE\n}";

	private const string findCodeTemplate = "\tpublic Row Find_$COLUMN(string find)\n\t{\n\t\treturn rowList.Find(x => x.$COLUMN == find);\n\t}\n\tpublic List<Row> FindAll_$COLUMN(string find)\n\t{\n\t\treturn rowList.FindAll(x => x.$COLUMN == find);\n\t}\n";

	public static string Generate(string csvText, string className)
	{
		return null;
	}
}
